# Generated by Django 3.2.4 on 2021-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210822_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
