# Generated by Django 3.2.4 on 2021-08-22 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_task_create_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_on',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
