# Generated by Django 3.2.4 on 2021-07-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default='some text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='commetns_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_on',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
