# Generated by Django 3.2.4 on 2021-07-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportal',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
