FROM python:3.9.5-buster
RUN pip install -U pip
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY ./app .
EXPOSE 5000/tcp
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
CMD [ "flask", "run", "--host=0.0.0.0"]