# Generated by Django 3.2.4 on 2021-08-22 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_commetns_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_on',
            field=models.TimeField(default=datetime.datetime(2021, 8, 22, 19, 5, 59, 388962, tzinfo=utc)),
        ),
    ]
