# Generated by Django 3.2.4 on 2021-08-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20210823_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.statusmember'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.statustask'),
        ),
    ]
